language: 'python'

python:
  - '3.5.2'

install:
  - pip install -r requirements.txt

before_script:
  - export config="../instance/config.py"

script:
  - pytest --cov=app/api
  - coveralls

after_success:
  - coveralls